#!/bin/bash
# Configuration values for SLURM job submission.
# One leading hash ahead of the word SBATCH is not a comment, but two are.
#SBATCH --job-name="satrAlign" # friendly name for job.
#SBATCH --nodes=1                      # ensure cores are on one node
#SBATCH --ntasks=1                     # run a single task
#SBATCH --cpus-per-task=10              # number of cores/threads requested.
#SBATCH --mem=32gb                      # memory requested.
#SBATCH --partition=20                 # partition (queue) to use
#SBATCH --output star-align-%j.out   # name of output file.  %j is jobid
##SBATCH --mail-type=ALL               # send email on job start/finish.
##SBATCH --mail-user=linyong@wi.mit.edu

# This is the actual section for commands to run
date

STAR --runThreadN 10 --outFilterMultimapNmax 20  --genomeDir /lab/solexa_page/linyong/dir-star-genome-index-oh75 --readFilesIn r1.fq  r2.fq   --outSAMtype BAM Unsorted --outSAMunmapped Within --outSAMattributes Standard

date

samtools sort -n -@ 6 -o MGB_022.name.multimap20.bam Aligned.out.bam
htseq-count  --mode=intersection-nonempty --nonunique=all  --stranded=no --idattr=gene_id --format=bam --additional-attr=gene_name --order=name --type=exon  MGB_022.name.multimap20.bam /lab/solexa_page/linyong/gencode/gencode.v42.primary_assembly.annotation.gtf  > MGB_022.2.multimap20.nonunique.genecount

date

# Uncomment the last line to email output file to specified address.
# Slurm doesn't do this automatically, regardless of the mail-type setting above.
#/usr/bin/mail -s "$SLURM_JOB_NAME $SLURM_JOB_ID" your_username@wi.mit.edu < friendlyname-${SLURM_JOB_ID}.out

linyong@tak /lab/solexa_page/linyong$ cat Log.final.out
                                 Started job on |	Jan 21 15:26:33
                             Started mapping on |	Jan 21 15:28:15
                                    Finished on |	Jan 21 15:36:58
       Mapping speed, Million of reads per hour |	421.89

                          Number of input reads |	61291131
                      Average input read length |	149
                                    UNIQUE READS:
                   Uniquely mapped reads number |	55960412
                        Uniquely mapped reads % |	91.30%
                          Average mapped length |	148.90
                       Number of splices: Total |	21656799
            Number of splices: Annotated (sjdb) |	21150908
                       Number of splices: GT/AG |	21350841
                       Number of splices: GC/AG |	155142
                       Number of splices: AT/AC |	14536
               Number of splices: Non-canonical |	136280
                      Mismatch rate per base, % |	0.26%
                         Deletion rate per base |	0.01%
                        Deletion average length |	1.51
                        Insertion rate per base |	0.01%
                       Insertion average length |	1.27
                             MULTI-MAPPING READS:
        Number of reads mapped to multiple loci |	4152550
             % of reads mapped to multiple loci |	6.78%
        Number of reads mapped to too many loci |	22987
             % of reads mapped to too many loci |	0.04%
                                  UNMAPPED READS:
  Number of reads unmapped: too many mismatches |	0
       % of reads unmapped: too many mismatches |	0.00%
            Number of reads unmapped: too short |	1133542
                 % of reads unmapped: too short |	1.85%
                Number of reads unmapped: other |	21640
                     % of reads unmapped: other |	0.04%
                                  CHIMERIC READS:
                       Number of chimeric reads |	0
                            % of chimeric reads |	0.00%
