#!/bin/bash
# Configuration values for SLURM job submission.
# One leading hash ahead of the word SBATCH is not a comment, but two are.
#SBATCH --job-name="fasterq-dump" # friendly name for job.
#SBATCH --time=21-00                    # run time for job
#SBATCH --nodes=1                      # ensure cores are on one node
#SBATCH --ntasks=1                     # run a single task
#SBATCH --cpus-per-task=30              # number of cores/threads requested.
#SBATCH --mem=200gb                      # memory requested.
#SBATCH --partition=20                 # partition (queue) to use
#SBATCH --output out-oct-27-100
#SBATCH --mail-type=ALL               # send email on job start/finish.
#SBATCH --mail-user=linyong@wi.mit.edu

# This is the actual section for commands to run

# Uncomment the last line to email output file to specified address.
# Slurm doesn't do this automatically, regardless of the mail-type setting above.
#/usr/bin/mail -s "$SLURM_JOB_NAME $SLURM_JOB_ID" your_username@wi.mit.edu < friendlyname-${SLURM_JOB_ID}.out

bash  /lab/solexa_page/linyong/gtex-dna/dir-dna-sra/script-download-fastq-GTEx-control-acc  SAMN04595808
bash  /lab/solexa_page/linyong/gtex-dna/dir-dna-sra/script-download-fastq-GTEx-control-acc  SAMN04596823
bash  /lab/solexa_page/linyong/gtex-dna/dir-dna-sra/script-download-fastq-GTEx-control-acc  SAMN03877550
bash  /lab/solexa_page/linyong/gtex-dna/dir-dna-sra/script-download-fastq-GTEx-control-acc  SAMN03877668
bash  /lab/solexa_page/linyong/gtex-dna/dir-dna-sra/script-download-fastq-GTEx-control-acc  SAMN03877936
bash  /lab/solexa_page/linyong/gtex-dna/dir-dna-sra/script-download-fastq-GTEx-control-acc  SAMN03877615
bash  /lab/solexa_page/linyong/gtex-dna/dir-dna-sra/script-download-fastq-GTEx-control-acc  SAMN03878036
bash  /lab/solexa_page/linyong/gtex-dna/dir-dna-sra/script-download-fastq-GTEx-control-acc  SAMN03877778
bash  /lab/solexa_page/linyong/gtex-dna/dir-dna-sra/script-download-fastq-GTEx-control-acc  SAMN04596783
bash  /lab/solexa_page/linyong/gtex-dna/dir-dna-sra/script-download-fastq-GTEx-control-acc  SAMN03877949

