#!/bin/bash
# Configuration values for SLURM job submission.
# One leading hash ahead of the word SBATCH is not a comment, but two are.
#SBATCH --job-name="satrAlign" # friendly name for job.
#SBATCH --nodes=1                      # ensure cores are on one node
#SBATCH --ntasks=1                     # run a single task
#SBATCH --cpus-per-task=10              # number of cores/threads requested.
#SBATCH --mem=32gb                      # memory requested.
#SBATCH --partition=20                 # partition (queue) to use
#SBATCH --output star-align-%j.out   # name of output file.  %j is jobid
##SBATCH --mail-type=ALL               # send email on job start/finish.
##SBATCH --mail-user=linyong@wi.mit.edu

# This is the actual section for commands to run
date

STAR --runThreadN 10 --outFilterMultimapNmax 20  --genomeDir /lab/solexa_page/linyong/dir-star-genome-index-oh75 --readFilesIn r1.fq  r2.fq   --outSAMtype BAM Unsorted --outSAMunmapped Within --outSAMattributes Standard

date

samtools sort -n -@ 6 -o MGB_022.name.multimap20.bam Aligned.out.bam
htseq-count  --mode=intersection-nonempty --nonunique=all  --stranded=no --idattr=gene_id --format=bam --additional-attr=gene_name --order=name --type=exon  MGB_022.name.multimap20.bam /lab/solexa_page/linyong/gencode/gencode.v42.primary_assembly.annotation.gtf  > MGB_022.2.multimap20.nonunique.genecount

date

# Uncomment the last line to email output file to specified address.
# Slurm doesn't do this automatically, regardless of the mail-type setting above.
#/usr/bin/mail -s "$SLURM_JOB_NAME $SLURM_JOB_ID" your_username@wi.mit.edu < friendlyname-${SLURM_JOB_ID}.out

