#!/bin/bash
# Configuration values for SLURM job submission.
# One leading hash ahead of the word SBATCH is not a comment, but two are.
#SBATCH --job-name="star-map-SE" # friendly name for job.
#SBATCH --nodes=1                      # ensure cores are on one node
#SBATCH --ntasks=1                     # run a single task
#SBATCH --cpus-per-task=5              # number of cores/threads requested.
#SBATCH --mem=80gb                      # memory requested.
#SBATCH --partition=20                 # partition (queue) to use
#SBATCH --output "out-dec-1-2023"   # name of output file.  %j is jobid
#SBATCH --mail-type=ALL               # send email on job start/finish.
#SBATCH --mail-user=linyong@wi.mit.edu

#


ls  /lab/page_scratch/helen/lukas/mouse/GB/*.fastq | grep -v "_[12].fastq$"  | while read ll
do
 pre=`echo "$ll" | sed 's/.fastq//' `
 rm Aligned.out.bam

 STAR --runThreadN 4 --outFilterMultimapNmax 20  --genomeDir /lab/solexa_page/linyong/dir-star-genome-index-mouse-oh150-chr --readFilesIn "$pre".fastq  --outSAMtype BAM Unsorted --outSAMunmapped Within --outSAMattributes Standard
 f=` echo "$ll" | sed 's/.fastq//' | sed 's#.*/mouse/GB/##' `
 cat Log.final.out > "$f.STAR.log"
 htseq-count  --mode=union --stranded=no --idattr=gene_id --format=bam --additional-attr=gene_name --order=name --type=exon  Aligned.out.bam /lab/solexa_page/linyong/mouse-genome/gencode.vM31.primary_assembly.annotation.gtf  > "$f.counts_gene"
 htseq-count  --mode=union --stranded=reverse --idattr=gene_id --format=bam --additional-attr=gene_name --order=name --type=exon  Aligned.out.bam  /lab/solexa_page/linyong/mouse-genome/gencode.vM31.primary_assembly.annotation.gtf  > "$f.stranded.counts_gene"
 htseq-count  --mode=union --stranded=yes --idattr=gene_id --format=bam --additional-attr=gene_name --order=name --type=exon  Aligned.out.bam  /lab/solexa_page/linyong/mouse-genome/gencode.vM31.primary_assembly.annotation.gtf  > "$f.stranded.same.counts_gene"
 echo -n "un-strand	" >> "$f.STAR.log"
 grep -iw ACTB  "$f.counts_gene" | grep -v ps1 >> "$f.STAR.log"
 echo -n "strand-reverse	" >> "$f.STAR.log"
 grep -iw ACTB  "$f.stranded.counts_gene" | grep -v ps1 >> "$f.STAR.log"
 echo -n "strand-yes	"  >> "$f.STAR.log"
 grep -iw ACTB  "$f.stranded.same.counts_gene" | grep -v ps1 >> "$f.STAR.log"

 rm Aligned.out.bam
 
done

###samtools sort -n -@ 6 -o MGB_022.name.multimap20.bam Aligned.out.bam

