#!/bin/bash
# Configuration values for SLURM job submission.
# One leading hash ahead of the word SBATCH is not a comment, but two are.
#SBATCH --job-name="autism-star-map" # friendly name for job.
#SBATCH --nodes=1                      # ensure cores are on one node
#SBATCH --ntasks=1                     # run a single task
#SBATCH --cpus-per-task=5              # number of cores/threads requested.
#SBATCH --mem=80gb                      # memory requested.
#SBATCH --partition=20                 # partition (queue) to use
#SBATCH --output out-aug-16-1245
#SBATCH --mail-type=ALL               # send email on job start/finish.
#SBATCH --mail-user=linyong@wi.mit.edu

# This is the actual section for commands to run

# Uncomment the last line to email output file to specified address.
# Slurm doesn't do this automatically, regardless of the mail-type setting above.
#/usr/bin/mail -s "$SLURM_JOB_NAME $SLURM_JOB_ID" your_username@wi.mit.edu < friendlyname-${SLURM_JOB_ID}.out

ls | grep -i fastq |  sed 's/\*$//' | while read ll
do
 echo "---------------------------"

 f=`echo "$ll" | sed 's/.fastq.gz//' `
 ls -lh "$ll"
 ###fq -> STAR align
 rm Aligned.out.bam 
 STAR --runThreadN 4 --outFilterMultimapNmax 20  --genomeDir /lab/solexa_page/linyong/dir-star-genome-index-oh75 --readFilesIn "$ll" --readFilesCommand zcat   --outSAMtype BAM Unsorted --outSAMunmapped Within --outSAMattributes Standard
 cat Log.final.out > "$f.STAR.stranded.log"
###samtools sort -n -@ 6 -o MGB_022.name.multimap20.bam Aligned.out.bam

 htseq-count  --mode=union --stranded=reverse --idattr=gene_id --format=bam --additional-attr=gene_name --order=name --type=exon  Aligned.out.bam /lab/solexa_page/linyong/gencode/gencode.v42.primary_assembly.noPar.annotation.gtf   > "$f.stranded.counts-gene"
 rm Aligned.out.bam 
 grep -w ACTB  "$f.counts_gene" >> "$f.STAR.stranded.log"
 grep -w GAPDH "$f.counts_gene" >> "$f.STAR.stranded.log"
 cat "$f.STAR.stranded.log"
done

